server:
  port: 8888

logging:
  path: logs
  file: test.log

spring:
  application:
    name: dubbotestapi
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/interfacecource?useUnicode=true&&characterEncoding=UTF-8&&serverTimezone=UTC
    username: root
    password: test1234567

mybatis:
  type-aliases-package: com.mybatis.store.config
  mapper-locations:
  - mapper/*